services:
  - type: web
    name: proxytea-backend
    env: node
    plan: free
    region: oregon
    branch: PRODUCTION_DEPLOY
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://proxceptadmin:MONGOatflagmate2026@proxcept-clustor.unamvf3.mongodb.net/superdebug?retryWrites=true&w=majority&appName=PROXCEPT-CLUSTOR

      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_BASE_PATH
        sync: false
      - key: PRODUCTION_DOMAIN
        value: https://proxytea.onrender.com,https://proxytea.hatchable.site,https://proxytea.com

